### ISSUE TITLE
ftype bugs

### ISSUE THREAD

**Issue by nobananasforyou** [AmusementClub/vs-dfttest2#5]
Hello!

Upon testing, I found that ftype's modes 2-4 do not function properly. Here's an example image.

![bug vpy - 9142](https://user-images.githubusercontent.com/50061008/198377751-34abc1dc-53da-4293-8e5e-b815f43b1a51.png)

Kind Regards

**Comment by WolframRhodium** [comment]
Hi. This should be an expected behaviour. Fttpe 2/3/4 multiples the Fourier coefficients by `sigma`, which by default amplifies the signal. Please verify that different backends produce similar results to `VapourSynthDFFTTest`.

**Comment by nobananasforyou** [comment]
I've only got a CPU so cannot test different backends. I get that ftype 2/3/4 amplifies the signal, however, the noise gets imprinted on the output. So is this option for debugging or does it serve another purpose?

**Comment by WolframRhodium** [comment]
You could suppress the signal by changing the value of `sigma` (or `slocation`, `ss{x, y, t}) to be a number less than 1, on the other hand.

**Comment by AkarinVS** [comment]
To put it another way, the behavior of dfttest2 is consistent with the original [VapourSynth-DFTTest](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DFTTest).

The artefacts you observed are due to the way default parameters interact. You have to adjust `sigma`/`slocation`/`sst`/`ssx`/`ssy` to remove them.
